
/**
 * @file crypto_aes.c
 * @date 2015-10-09
 *
 * NOTE:
 * This file is generated by DAVE. Any manual modification done to this file will be lost when the code is regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * CRYPTO_AES v4.0.8 - Encrypt/Decrypt user data using the AES standard
 *
 * Copyright (c) 2015, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG (dave@infineon.com).
 ***********************************************************************************************************************
 *
 * Change History
 * --------------
 *
 * 2015-02-16:
 *     - Initial version <br>
 *
 * 2015-04-21:
 *     - CRYPTO_AES_Reset() now returns nothing <br>
 *     - Symbolic name changes in CRYPTO_AES_STATUS_t <br>
 *     - CRYPTO_AES_Encrypt() returns "invalid data len" in ECB mode if len is not 16 <br>
 *     - CRYPTO_AES_Decrypt() returns "invalid data len" in ECB mode if len is not 16 <br>
 *
 * 2015-06-20:
 *     - Update license/version information <br>
 *
 * @endcond
 */

/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/

#include <string.h>
#include "crypto_aes.h"

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * LOCAL DATA
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * LOCAL ROUTINES
 **********************************************************************************************************************/

/**********************************************************************************************************************
 * API IMPLEMENTATION
 **********************************************************************************************************************/

/*
 * Retrieve the version of the CRYPTO_AES APP
 */
DAVE_APP_VERSION_t CRYPTO_AES_GetAppVersion(void)
{
  DAVE_APP_VERSION_t version;

  version.major = CRYPTO_AES_MAJOR_VERSION;
  version.minor = CRYPTO_AES_MINOR_VERSION;
  version.patch = CRYPTO_AES_PATCH_VERSION;

  return version;
}

/*
 * Restore the default values of mode, keysize and
 * initialization vector
 */
void CRYPTO_AES_Reset(CRYPTO_AES_t *obj)
{
  obj->key_size = CRYPTO_AES_KEY_SIZE_128;
  obj->mode = CRYPTO_AES_MODE_ECB;
  obj->key_status = CRYPTO_AES_KEY_STATUS_NOT_SET;
  memset(obj->init_vector, 0, AES_BLOCK_SIZE);
}

/*
 * Initialize CIPHER_AES object with APP GUI
 * configuration
 */
CRYPTO_AES_STATUS_t CRYPTO_AES_Init(CRYPTO_AES_t *obj)
{
  CRYPTO_AES_STATUS_t status;

  /* Setup the initialization vector */
  memcpy(obj->init_vector, crypto_aes_init_vector, AES_BLOCK_SIZE);

  /* Now, set the key */
  status = CRYPTO_AES_SetKey(obj, crypto_aes_encryption_key, obj->encryption_operation);

  return (status);
}

/*
 * Initialize CIPHER_AES object with user encryption key
 *
 * The key can be assigned for either an encryption or a
 * decryption operation. If `encryption_mode' is set to true,
 * the key is then assigned for an encipher operation.
 */
CRYPTO_AES_STATUS_t CRYPTO_AES_SetKey(CRYPTO_AES_t *obj, const uint8_t *key, bool encryption_mode)
{
  CRYPTO_AES_STATUS_t status = CRYPTO_AES_STATUS_SUCCESS;
  int32_t res = (int32_t)0;

  if (encryption_mode == AES_ENCRYPT)
  {
    res = AES_set_encrypt_key(key, obj->key_size, &obj->expanded_key);
    obj->key_status = CRYPTO_AES_KEY_STATUS_ENCRYPT;
  }
  else
  {
    if ((obj->mode == CRYPTO_AES_MODE_ECB) || (obj->mode == CRYPTO_AES_MODE_CBC))
    {
      res = AES_set_decrypt_key(key, obj->key_size, &obj->expanded_key);
      obj->key_status = CRYPTO_AES_KEY_STATUS_DECRYPT;
    }
    else
    {
      status = CRYPTO_AES_STATUS_INVALID_MODE;
    }
  }

  if (res == -1)
  {
    status = CRYPTO_AES_STATUS_INVALID_KEY;
  }

  if (res == -2)
  {
    status = CRYPTO_AES_STATUS_INVALID_KEY_LENGTH;
  }

  return (status);
}

/*
 * A convenient wrapper function to encipher user
 * data in various AES confidentiality modes
 */
CRYPTO_AES_STATUS_t CRYPTO_AES_Encrypt(CRYPTO_AES_t *obj,
                                       uint8_t *out_buf,
                                       const uint8_t *in_buf,
                                       uint32_t num_bytes)
{
  CRYPTO_AES_STATUS_t status = CRYPTO_AES_STATUS_SUCCESS;

  /*
   * These variables below are only used in a few modes
   */
#if defined (CRYPTO_AES_BUILD_MODE_CFB) ||\
    defined (CRYPTO_AES_BUILD_MODE_OFB) ||\
    defined (CRYPTO_AES_BUILD_MODE_CTR)
  uint32_t num = 0U;
#endif

#if defined (CRYPTO_AES_BUILD_MODE_CTR)
  uint8_t ecount_buf[AES_BLOCK_SIZE];
#endif

  /*
   * Check if the key is set for encryption
   */
  if (obj->key_status != CRYPTO_AES_KEY_STATUS_ENCRYPT)
  {
    status = CRYPTO_AES_STATUS_INVALID_KEY;
  }
  /*
   * Check data length
   * Note: Special case for ECB mode -> Return
   * "invalid data length" if the length is not
   * 16.
   */
  else if (((num_bytes % (uint32_t)AES_BLOCK_SIZE) != 0U) ||
           (num_bytes == 0U) ||
           ((obj->mode == CRYPTO_AES_MODE_ECB) && (num_bytes != 16U)))
  {
    status = CRYPTO_AES_STATUS_INVALID_DATA_LENGTH;
  }
  /*
   * Invoke appropriate encryption function,
   * for the selected encryption mode
   */
  else
  {
    switch (obj->mode)
    {
#ifdef CRYPTO_AES_BUILD_MODE_ECB
      case CRYPTO_AES_MODE_ECB:
        AES_ecb_encrypt(in_buf, out_buf, &obj->expanded_key, 1);
        break;
#endif
#ifdef CRYPTO_AES_BUILD_MODE_CBC
      case CRYPTO_AES_MODE_CBC:
    	AES_cbc_encrypt(in_buf, out_buf, num_bytes, &obj->expanded_key, obj->init_vector, 1);
    	break;
#endif
#ifdef CRYPTO_AES_BUILD_MODE_CFB
      case CRYPTO_AES_MODE_CFB:
    	AES_cfb128_encrypt(in_buf, out_buf, num_bytes, &obj->expanded_key, obj->init_vector, (int*)&num, 1);
    	break;
#endif
#ifdef CRYPTO_AES_BUILD_MODE_OFB
      case CRYPTO_AES_MODE_OFB:
        AES_ofb128_encrypt(in_buf, out_buf, num_bytes, &obj->expanded_key, obj->init_vector, (int*)&num);
        break;
#endif
#ifdef CRYPTO_AES_BUILD_MODE_CTR
      case CRYPTO_AES_MODE_CTR:
    	AES_ctr128_encrypt(in_buf,
                           out_buf,
                           num_bytes,
                           &obj->expanded_key,
                           obj->init_vector,
                           ecount_buf,
                           (unsigned int *)&num);
    	break;
#endif
      default:
        status = CRYPTO_AES_STATUS_INVALID_MODE;
        break;
    }
  }

  return (status);
}

/*
 * A convenient wrapper function to decipher user
 * data in various AES confidentiality modes
 */
CRYPTO_AES_STATUS_t CRYPTO_AES_Decrypt(CRYPTO_AES_t *obj,
                                       uint8_t *out_buf,
                                       const uint8_t *in_buf,
                                       uint32_t num_bytes)
{
  CRYPTO_AES_STATUS_t status = CRYPTO_AES_STATUS_SUCCESS;
  /*
   * These variables below are only used in a few modes
   */
#if defined (CRYPTO_AES_BUILD_MODE_CFB) ||\
    defined (CRYPTO_AES_BUILD_MODE_OFB) ||\
    defined (CRYPTO_AES_BUILD_MODE_CTR)
  uint32_t num = 0;
#endif

#if defined (CRYPTO_AES_BUILD_MODE_CTR)
  uint8_t ecount_buf[AES_BLOCK_SIZE];
#endif

  /*
   * Check if the key is set for decryption
   */
  if (obj->key_status != CRYPTO_AES_KEY_STATUS_DECRYPT)
  {
    status = CRYPTO_AES_STATUS_INVALID_KEY;
  }
  /*
   * Check data length
   * Note: Special case for ECB mode -> Return
   * "invalid data length" if the length is not
   * 16.
   */
  else if (((num_bytes % (uint32_t)AES_BLOCK_SIZE) != 0U) ||
           (num_bytes == 0U) ||
           ((obj->mode == CRYPTO_AES_MODE_ECB) && (num_bytes != 16U)))
  {
    status = CRYPTO_AES_STATUS_INVALID_DATA_LENGTH;
  }
  /*
   * Invoke appropriate decrypt function
   * for the selected decryption mode
   */
  else
  {
    switch (obj->mode)
    {
#ifdef CRYPTO_AES_BUILD_MODE_ECB
      case CRYPTO_AES_MODE_ECB:
        AES_ecb_encrypt(in_buf, out_buf, &obj->expanded_key, 0);
        break;
#endif
#ifdef CRYPTO_AES_BUILD_MODE_CBC
      case CRYPTO_AES_MODE_CBC:
    	AES_cbc_encrypt(in_buf, out_buf, num_bytes, &obj->expanded_key, obj->init_vector, 0);
    	break;
#endif	
#ifdef CRYPTO_AES_BUILD_MODE_CFB
      case CRYPTO_AES_MODE_CFB:
    	AES_cfb128_encrypt(in_buf, out_buf, num_bytes, &obj->expanded_key, obj->init_vector, (int *)&num, 0);
    	break;
#endif
#ifdef CRYPTO_AES_BUILD_MODE_OFB
      case CRYPTO_AES_MODE_OFB:
        AES_ofb128_encrypt(in_buf, out_buf, num_bytes, &obj->expanded_key, obj->init_vector, (int *)&num);
        break;
#endif
#ifdef CRYPTO_AES_BUILD_MODE_CTR
      case CRYPTO_AES_MODE_CTR:
    	AES_ctr128_encrypt(in_buf,
                           out_buf,
                           num_bytes,
                           &obj->expanded_key,
                           obj->init_vector,
                           ecount_buf,
                           (unsigned int *)&num);
    	break;
#endif
      default:
        status = CRYPTO_AES_STATUS_INVALID_MODE;
        break;
    }
  }

  return (status);
}
